### ISSUE TITLE
Exceptions are not being flushed from the server to the client

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/protege-ontology-client#28] opened 2016-07-20 21:30 UTC
From my tests this is happening with exceptions in general. The server throws some specific exception, but the client only gets a general "server internal exception 500", with no information about what went wrong. For example, as guest I tried to commit some changes and got the window in the screenshot below within Protege.

![screen shot 2016-07-20 at 13 49 46](https://cloud.githubusercontent.com/assets/4361140/17003030/ff831e50-4e82-11e6-9fd9-f644e30288f4.png)

As a user, I've no idea what to do with this. The server reported the actual exception, which was:

```
14:29:09 [XNIO-2 task-6] ERROR - [Request from UserIdImpl{id=guest} (NameImpl{name=Guest User}) - NameImpl{name=Add axiom}] Request rejected. Operations are not allowed
14:29:09 [XNIO-2 task-6] ERROR - UT005071: Undertow request failed HttpServerExchange{ POST /nci_protege/commit request {Connection=[Keep-Alive], Authorization=[Basic Z3Vlc3Q6MzZhNGZkODYtZTgxNC00ZDdhLWI3MjktNDQ1MTdiNjk3NTA2], Accept-Encoding=[gzip], Content-Length=[46976], User-Agent=[okhttp/3.0.0-RC1], Host=[localhost:8080]} response {}}
org.protege.editor.owl.server.api.exception.ServerServiceException: User has no permission for 'Add axiom' operation
    at org.protege.editor.owl.server.policy.AccessControlFilter.evaluateCommitBundle(AccessControlFilter.java:244) ~[org.protege.owl.server.jar:na]
    at org.protege.editor.owl.server.policy.AccessControlFilter.commit(AccessControlFilter.java:214) ~[org.protege.owl.server.jar:na]
    at org.protege.editor.owl.server.http.handlers.HTTPChangeService.handleRequest(HTTPChangeService.java:50) ~[org.protege.owl.server.jar:na]
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:198) ~[org.protege.owl.server.jar:na]
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:788) ~[org.protege.owl.server.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_74]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_74]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_74]
Caused by: org.protege.editor.owl.server.api.exception.OperationNotAllowedException: User has no permission for 'Add axiom' operation
    at org.protege.editor.owl.server.api.exception.OperationNotAllowedException.create(OperationNotAllowedException.java:34) ~[org.protege.owl.server.jar:na]
    at org.protege.editor.owl.server.policy.AccessControlFilter.evaluateCommitBundle(AccessControlFilter.java:242) ~[org.protege.owl.server.jar:na]
    ... 7 common frames omitted
```

**Comment by bdionne** [comment] 2016-07-21 12:03
When you say in general do you mean with respect to commits or other operations as well? Which others are presenting problems?

I haven't really worked out the best way to materialize all these exceptions, but the lion's share of the fine-grained metaproject editing methods have been moved to the client, so exceptions there should be wrapped in `ClientRequestException` and you should be able to access the causes.

I've surfaced the [ServerServiceExceptions](https://github.com/protegeproject/protege-client/commit/2a3dce93bf6bbdfac412cf64a309c0ee6ca1262e) that are thrown on commits

![authorized](https://cloud.githubusercontent.com/assets/31741/17020555/392dfdc2-4f10-11e6-826c-e87e865b0584.png)

**Comment by johardi** [comment] 2016-07-22 16:50
I'd like to propose a way to propagate exception from server to client. The idea is like this:
1. All server methods must throw the exceptions, rather than just to catch them.
2. All these exceptions must be wrapped in [ServerException](https://github.com/protegeproject/protege-server/blob/http-metaproject-integration/src/main/java/org/protege/editor/owl/server/http/exception/ServerException.java). It is mandatory the ServerException contains the [StatusCode](https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/util/StatusCodes.java) and the error message. (See https://en.wikipedia.org/wiki/List_of_HTTP_status_codes for each status code). To include the cause exception is optional (imo, it's better to flush it using the server's logger)
3. When the exception reaches the handlers, convert it as a response header (e.g., [like this](https://github.com/protegeproject/protege-server/blob/http-metaproject-integration/src/main/java/org/protege/editor/owl/server/http/handlers/AuthenticationHandler.java#L48-L51)).
4. And then when finally the response message reaches the client (i.e., LocalHttpClient), implement the exception handler based on the StatusCode (e.g., [like this](https://github.com/protegeproject/protege-client/blob/http-metaproject-integration/src/main/java/org/protege/editor/owl/client/LocalHttpClient.java#L1027-L1041))

There are two benefits with this approach:
1. It's lightweight. The server doesn't have to serialize and transmit the exception object. The exception is encoded by the StatusCode and the message.
2. It's module independent. Since the message passing is using string, the client and server are very much independent.

Let me know what do you think?

**Comment by bdionne** [comment] 2016-07-23 09:22
+1 - I think this is a good approach, simple. We'll have to map the existing exceptions to reasonable `HTTP` codes, and I think rework some of the legacy objects from the RMI implementation. For example in the [changes](https://github.com/protegeproject/protege-server/blob/http-metaproject-integration/src/main/java/org/protege/editor/owl/server/http/handlers/HTTPChangeService.java#L49-L54) handler where we call commit, it throws three exceptions though in practice it only throws `ServerServiceException` which will embed one of the other two. Passing this to the [client](https://github.com/protegeproject/protege-client/blob/http-metaproject-integration/src/main/java/org/protege/editor/owl/client/LocalHttpClient.java#L389-L403) and then unbundling it there to determine which to throw up to the `GUI` is awkward, and as you note the `GUI` only needs to put the error message into a dialog.

**Comment by bdionne** [comment] 2016-07-29 10:53
Let me just reopen this until I make all the edit tab changes, which I fully expected would be needed, We dropped the snapshot put for some reason (see #27)

**Comment by bdionne** [comment] 2016-07-29 20:47
these all look good to me now - closing this

**Closed as completed by bdionne** 2016-07-29 20:47 UTC
