### ISSUE TITLE
Server menu should reflect login state

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege-ontology-client#49] opened 2016-08-01 14:54 UTC
When expired tokens result in client side exceptions, server menu is not updated to reflect state

**Comment by johardi** [comment] 2016-08-02 18:57
I couldn't reproduce the error. The menu items are disabled after the client senses LoginTimeoutException.

**Comment by bdionne** [comment] 2016-08-03 14:24
After the timeout, I requested the change history and got the popup indicating I needed to logout/login again. When I look at the server menu I see:

![screen shot 2016-08-03 at 10 22 09 am](https://cloud.githubusercontent.com/assets/31741/17368998/6c92993a-5964-11e6-877d-9afd6d78c138.png)

But at that point I'm already logged out, shouldn't the login be enabled, or should I be prompted to login?

**Comment by johardi** [comment] 2016-08-11 18:06
Fixed via https://github.com/protegeproject/protege-client/commit/f2634cfdd14522b9087ce74226f1e22dbd39096f, https://github.com/protegeproject/protege-client/commit/fbe0fd784259185905735e50e3bf997e19a72752

**Closed as completed by johardi** 2016-08-11 18:06 UTC
