### ISSUE TITLE
Logout sometimes wedges protege

### ISSUE THREAD

**Issue by bdionne** [protegeproject/protege-ontology-client#31] opened 2016-07-21 17:47 UTC
Occasionally logout throws the detaching bad listener exception:

[31mException thrown by listener: org.protege.editor.owl.client.ClientSession$1.  Detatching bad listener.[0;39m 

After which one can't do anything useful other than exiting the app:

![screen shot 2016-07-21 at 1 45 53 pm](https://cloud.githubusercontent.com/assets/31741/17032941/b2cd582e-4f49-11e6-928a-f51a7456f1a2.png)

**Comment by johardi** [comment] 2016-07-21 23:39
This is duplicate of issue #20

**Comment by johardi** [comment] 2016-07-22 04:16
Fix via https://github.com/protegeproject/protege-client/commit/e080c6fb4617917c2216225d8e6d54e9f73bd02a

**Closed as completed by johardi** 2016-07-22 04:16 UTC
